# Generated by Django 5.0.6 on 2024-06-02 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
