# Generated by Django 5.0.6 on 2024-07-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('reading', 'Read a book'), ('financial', 'Become financially secure'), ('exercise', 'Exercise regularly'), ('healthy_eating', 'Eat healthy'), ('learning', 'Learn a new skill'), ('travel', 'Travel to a new place'), ('mindfulness', 'Practice mindfulness'), ('networking', 'Build professional network'), ('volunteer', 'Volunteer for a cause'), ('hobby', 'Develop a new hobby')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.ManyToManyField(blank=True, to='api.goal'),
        ),
    ]
