# Generated by Django 5.0.6 on 2024-07-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_interest_remove_profile_goals_profile_interests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_working_on', models.TextField()),
                ('progress_towards_goals', models.TextField()),
                ('challenges', models.TextField()),
                ('one_year_goal', models.TextField()),
                ('five_year_goal', models.TextField()),
                ('achievements_feel_successful', models.TextField()),
                ('motivation', models.TextField()),
                ('values_principles', models.TextField()),
                ('resources_support', models.TextField()),
                ('skills_needed', models.TextField()),
            ],
        ),
    ]
