# Generated by Django 5.0.6 on 2024-07-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='due date'),
        ),
    ]
