# Generated by Django 5.0.6 on 2024-08-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_task_options_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'notifications'},
        ),
    ]
