# Generated by Django 5.0.6 on 2024-08-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_notifications_options_notifications_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='resources_support',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='skills_needed',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='values_principles',
        ),
    ]
