# Generated by Django 5.0.6 on 2024-08-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_interest_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='owner',
        ),
    ]
